[tool.poetry]
name = "ponyexpress"
version = "0.1.0"
description = "A multipurpose spidery crawler for social media platforms"
authors = ["Philipp Kessling <p.kessling@leibniz-hbi.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.4.0"
lxml = "^4.7.1"
SQLAlchemy = "^1.4.31"
loguru = "^0.6.0"
numpy = "^1.22.2"
requests = "^2.27.1"
click = "^8.0.3"
ImageHash = "^4.2.1"
psycopg2-binary = "^2.9.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
ipykernel = "^6.9.0"
pytest = "^7.0.0"
pdoc3 = "^0.10.0"

[tool.poetry.scripts]
ponyexpress = 'ponyexpress.cli:cli'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
